"""
profile_to_preset.py
--------------------

This script converts analysis profiles generated by ``full_stem_analyzer.py``
into high‑level engine presets that can be consumed by the Digital Velvet
Voice Engine plugin.  A preset contains simple, intuitive controls (e.g.,
brightness, warmth, pitch tightness) derived from the underlying acoustic
measurements.  These values are normalised between 0 and 1 where
appropriate.

Usage::

    python analysis/profile_to_preset.py [--presets-dir DIR] [--output-dir DIR]

If no output directory is provided, presets will be written to
``engine_presets/``.  A ``digital_velvet_default.json`` preset is also
generated by averaging all song presets.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple


def load_analysis_profiles(presets_dir: Path) -> Dict[str, Dict[str, object]]:
    """Load all analysis profiles (JSON files) from ``presets_dir``.

    Parameters
    ----------
    presets_dir : Path
        Directory containing analysis profiles.

    Returns
    -------
    profiles : dict
        Mapping from song key to profile dictionary.
    """
    profiles: Dict[str, Dict[str, object]] = {}
    for path in presets_dir.glob("*.json"):
        try:
            with path.open("r", encoding="utf-8") as f:
                data = json.load(f)
                song_key = path.stem
                profiles[song_key] = data
        except Exception:
            continue
    return profiles


def map_analysis_to_preset(analysis: Dict[str, object]) -> Dict[str, object]:
    """Convert an analysis profile into an engine preset.

    Parameters
    ----------
    analysis : dict
        A dictionary produced by ``full_stem_analyzer.analyze_audio``.

    Returns
    -------
    preset : dict
        Engine preset with normalised controls.  Fields:
        - brightness: 0–1, derived from spectral centroid
        - warmth: 0–1, inverse of brightness
        - pitch_tightness: 0–1, inversely related to pitch variability
        - compression_density: 0–1, proportional to RMS standard deviation
        - formant_shift: always 0 for now (reserved for future)
        - reverb_amount: default 0.3
        - delay_amount: default 0.1
        - air: copy of brightness (redundant macro for high‑frequency emphasis)
    """
    gf = analysis.get("global_features", {})
    # Brightness normalisation: divide by an upper bound (8000 Hz) and clamp
    brightness_raw = gf.get("spectral_centroid_mean", 0.0)
    brightness = max(0.0, min(brightness_raw / 8000.0, 1.0))
    warmth = 1.0 - brightness

    # Pitch tightness: lower variability => higher tightness
    pitch_mean = gf.get("pitch_mean_hz", 0.0)
    pitch_std = gf.get("pitch_std_hz", 0.0)
    tight_ratio = 0.0
    if pitch_mean > 0.0:
        tight_ratio = (pitch_std / pitch_mean)
    pitch_tightness = 1.0 - max(0.0, min(tight_ratio * 2.0, 1.0))

    # Compression density: proportional to RMS variability (scaled)
    rms_std = gf.get("rms_std", 0.0)
    compression_density = max(0.0, min(rms_std * 10.0, 1.0))

    # Formant shift placeholder: 0 means no shift (future use)
    formant_shift = 0.0

    # Default ambience
    reverb_amount = 0.3
    delay_amount = 0.1

    # Air (high‑frequency emphasis) derived from brightness
    air = brightness

    return {
        "brightness": round(brightness, 3),
        "warmth": round(warmth, 3),
        "pitch_tightness": round(pitch_tightness, 3),
        "compression_density": round(compression_density, 3),
        "formant_shift": round(formant_shift, 3),
        "reverb_amount": round(reverb_amount, 3),
        "delay_amount": round(delay_amount, 3),
        "air": round(air, 3),
    }


def average_presets(presets: List[Dict[str, object]]) -> Dict[str, float]:
    """Compute the average of a list of preset feature dictionaries.

    Parameters
    ----------
    presets : list of dict
        List of presets with the same keys and numeric values.

    Returns
    -------
    avg : dict
        Dictionary of averaged values.
    """
    if not presets:
        return {}
    keys = presets[0].keys()
    sums: Dict[str, float] = {k: 0.0 for k in keys}
    for p in presets:
        for k in keys:
            sums[k] += float(p.get(k, 0.0))
    return {k: round(sums[k] / len(presets), 3) for k in keys}


def main(argv: List[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Convert analysis profiles into engine presets")
    parser.add_argument("--presets-dir", type=str, default=str(Path(__file__).resolve().parent.parent / "presets"), help="Directory containing analysis profiles")
    parser.add_argument("--output-dir", type=str, default=str(Path(__file__).resolve().parent.parent / "engine_presets"), help="Directory to output engine presets")
    args = parser.parse_args(argv)

    presets_dir = Path(args.presets_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    analysis_profiles = load_analysis_profiles(presets_dir)
    if not analysis_profiles:
        print(f"No analysis profiles found in {presets_dir}")
        return

    engine_presets: Dict[str, Dict[str, float]] = {}
    for song_key, analysis in analysis_profiles.items():
        engine_presets[song_key] = map_analysis_to_preset(analysis)

    # Save each song preset
    for song_key, preset in engine_presets.items():
        preset_data = {
            "song": song_key,
            "features": preset,
        }
        with (output_dir / f"{song_key}.json").open("w", encoding="utf-8") as f:
            json.dump(preset_data, f, indent=2)
        print(f"Wrote preset for {song_key}")

    # Compute and save a global default preset
    avg_features = average_presets(list(engine_presets.values()))
    default_data = {
        "name": "digital_velvet_default",
        "features": avg_features,
    }
    with (output_dir / "digital_velvet_default.json").open("w", encoding="utf-8") as f:
        json.dump(default_data, f, indent=2)
    print("Wrote digital_velvet_default preset")


if __name__ == "__main__":
    main()